Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2020-09, with the labels that each got.

#173 Dockerized db2 test dependencies
  build/Scripts/run-integration-tests.ps1
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/IbmDb2AsyncTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/IbmDb2Tests.cs
  tests/Agent/IntegrationTests/UnboundedServices/db2/Dockerfile
  tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
  tests/Agent/IntegrationTests/UnboundedServices/unbounded-services-control.ps1
Labels: testing

#176 Dockerized oracle test dependencies
  tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
  tests/Agent/IntegrationTests/UnboundedServices/oracle/Dockerfile
Labels: testing

#175 Fit/eu support
  src/Agent/NewRelic/Agent/Configuration/IConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionInfo.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/HttpCollectorWire.cs
  tests/Agent/UnitTests/Core.UnitTest/Core.UnitTest.csproj
  tests/Agent/UnitTests/Core.UnitTest/CrossAgentTests/DataTransport/CollectorHostNameTests.cs
  tests/Agent/UnitTests/Core.UnitTest/CrossAgentTests/DataTransport/collector_hostname.json
Labels: net35

#194 Change Log Updates for 6.26 release
  src/Agent/CHANGELOG.md
Labels: net35

#182 Make use of the dockerized unbounded services optional
  build/Scripts/run-integration-tests.ps1
Labels: testing

#183 Modify project files to reduce warnings when building
  tests/Agent/IntegrationTests/Shared/MsSqlOleDbConfiguration.cs
  tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/MongoDB2_6Application/MongoDB2_6Application.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/MongoDB2_6CoreApplication/MongoDB2_6CoreApplication.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/MongoDBApplication/MongoDBApplication.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusReceiverHost/NServiceBusReceiverHost.csproj
Labels: testing

#193 Dockerized mysql test dependencies
  tests/Agent/IntegrationTests/Shared/MySqlConfiguration.cs
  tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Controllers/MySqlController.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySqlAsyncTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySqlTests.cs
  tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
  tests/Agent/IntegrationTests/UnboundedServices/mysql/Dockerfile
  tests/Agent/IntegrationTests/UnboundedServices/mysql/database.sql
Labels: testing

#207 Document use of the containerized services for the unbounded integration tests
  tests/Agent/IntegrationTests/UnboundedServices/README.md
  tests/Agent/IntegrationTests/UnboundedServices/example-secrets.json
  tests/Agent/IntegrationTests/UnboundedServices/unbounded-services-control.ps1
Labels: documentation, testing

#206 Refactor connection string parsing
  tests/Agent/IntegrationTests/Shared/ApplicationConfiguration.cs
  tests/Agent/IntegrationTests/Shared/Db2Configuration.cs
  tests/Agent/IntegrationTests/Shared/IntegrationTestConfiguration.cs
  tests/Agent/IntegrationTests/Shared/MongoDbConfiguration.cs
  tests/Agent/IntegrationTests/Shared/MsSqlConfiguration.cs
  tests/Agent/IntegrationTests/Shared/MySqlConfiguration.cs
  tests/Agent/IntegrationTests/Shared/OracleConfiguration.cs
  tests/Agent/IntegrationTests/Shared/PostgresConfiguration.cs
  tests/Agent/IntegrationTests/Shared/StackExchangeRedisConfiguration.cs
Labels: testing

#213 Refactor connection string parsing (#206)
  tests/Agent/IntegrationTests/Shared/Db2Configuration.cs
  tests/Agent/IntegrationTests/Shared/IntegrationTestConfiguration.cs
  tests/Agent/IntegrationTests/Shared/MsSqlConfiguration.cs
  tests/Agent/IntegrationTests/Shared/MySqlConfiguration.cs
  tests/Agent/IntegrationTests/Shared/OracleConfiguration.cs
  tests/Agent/IntegrationTests/Shared/PostgresConfiguration.cs
  tests/Agent/IntegrationTests/Shared/StackExchangeRedisConfiguration.cs
Labels: net35

#212 Net35 - Document docker services for unbounded tests
  tests/Agent/IntegrationTests/UnboundedServices/README.md
  tests/Agent/IntegrationTests/UnboundedServices/example-secrets.json
  tests/Agent/IntegrationTests/UnboundedServices/unbounded-services-control.ps1
Labels: documentation, net35

#208 Net35 - Integration Tests supporting P15 (New)
  tests/Agent/IntegrationTests/Applications/AspNetCoreMvcBasicRequestsApplication/Program.cs
  tests/Agent/IntegrationTests/Applications/BasicMvcApplication/Global.asax.cs
  tests/Agent/IntegrationTests/Applications/HttpCollector/App_Start/FilterConfig.cs
  tests/Agent/IntegrationTests/Applications/HttpCollector/App_Start/RouteConfig.cs
  tests/Agent/IntegrationTests/Applications/HttpCollector/App_Start/WebApiConfig.cs
  tests/Agent/IntegrationTests/Applications/HttpCollector/Controllers/AgentListenerController.cs
  tests/Agent/IntegrationTests/Applications/HttpCollector/Controllers/HomeController.cs
  tests/Agent/IntegrationTests/Applications/HttpCollector/Deploy/PrecompiledApp.config
  tests/Agent/IntegrationTests/Applications/HttpCollector/Deploy/Views/Home/Index.cshtml
  tests/Agent/IntegrationTests/Applications/HttpCollector/Deploy/Views/Web.config
  tests/Agent/IntegrationTests/Applications/HttpCollector/Deploy/Web.config
  tests/Agent/IntegrationTests/Applications/HttpCollector/Global.asax
  tests/Agent/IntegrationTests/Applications/HttpCollector/Global.asax.cs
  tests/Agent/IntegrationTests/Applications/HttpCollector/HttpCollector.csproj
  tests/Agent/IntegrationTests/Applications/HttpCollector/Properties/AssemblyInfo.cs
  tests/Agent/IntegrationTests/Applications/HttpCollector/Properties/PublishProfiles/LocalDeploy.pubxml
  tests/Agent/IntegrationTests/Applications/HttpCollector/Startup.cs
  tests/Agent/IntegrationTests/Applications/HttpCollector/Views/Home/Index.cshtml
  tests/Agent/IntegrationTests/Applications/HttpCollector/Views/Web.config
  tests/Agent/IntegrationTests/Applications/HttpCollector/Web.Debug.config
  tests/Agent/IntegrationTests/Applications/HttpCollector/Web.Release.config
  tests/Agent/IntegrationTests/Applications/HttpCollector/Web.config
  tests/Agent/IntegrationTests/Applications/MockNewRelic/Controllers/AgentListenerController.cs
  tests/Agent/IntegrationTests/Applications/MockNewRelic/MockNewRelic.csproj
  tests/Agent/IntegrationTests/Applications/MockNewRelic/Program.cs
  tests/Agent/IntegrationTests/Applications/MockNewRelic/Properties/launchSettings.json
  tests/Agent/IntegrationTests/Applications/MockNewRelic/README.md
  tests/Agent/IntegrationTests/Applications/MockNewRelic/Startup.cs
  tests/Agent/IntegrationTests/Applications/MockNewRelic/StreamMediaTypeInputFormatter.cs
  tests/Agent/IntegrationTests/Applications/MockNewRelic/appsettings.Development.json
  tests/Agent/IntegrationTests/Applications/MockNewRelic/appsettings.json
  tests/Agent/IntegrationTests/Applications/MockNewRelic/testcert.pfx
  tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogFile.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/ITestLogger.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplication.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplicationFixture.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteService.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/XUnitTestLogger.cs
  tests/Agent/IntegrationTests/IntegrationTests.sln
  tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/HttpCollectorFixture.cs
  tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/MockNewRelicFixture.cs
  tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/MvcWithCollectorFixture.cs
  tests/Agent/IntegrationTests/Shared/Models/HeaderValidationData.cs
Labels: net35

#215 Add DB2 client install instructions
  docs/integration-tests.md
Labels: documentation, testing

#214 WCF - Support CAT and DT over NetTCP
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Agent.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/ChannelFactoryWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/MethodInvokerWrapper.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFClientTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFClientTests_SelfHosted.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFServiceTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFServiceTests_SelfHosted.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFTestBase.cs
Labels: enhancement

#219 Add DB2 client install instructions
  docs/integration-tests.md
Labels: documentation, net35, testing

#225 AddNewRelicStartupFilter should only be added once.
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/GenericHostWebHostBuilderExtensionsWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Owin/ResolveAppWrapper.cs
Labels: bug

#228 v832 ChangeLog Updates
  src/Agent/CHANGELOG.md
Labels: chore

#232 Pr builder actions
  .github/workflows/all_solutions.yml
  src/Agent/NewRelic/Profiler/docker-compose.yml
  tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Controllers/IbmDb2Controller.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/IbmDb2AsyncTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/IbmDb2StoredProcedureTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/IbmDb2Tests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/IbmDb2BasicMvcFixture.cs
Labels: enhancement, testing

#251 Save Profiler artifacts for later use in workflow
  .github/workflows/all_solutions.yml
Labels: enhancement, testing

#235 Fix HttpClient instrumentation for .NET 5
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/HttpClient/Instrumentation.xml
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/HttpClient/SendAsync.cs
  src/Agent/NewRelic/Profiler/Configuration/InstrumentationConfiguration.h
  src/Agent/NewRelic/Profiler/MethodRewriter/IFunction.h
  src/Agent/NewRelic/Profiler/MethodRewriterTest/MockFunction.h
  src/Agent/NewRelic/Profiler/Profiler/Function.h
Labels: enhancement
