Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2020-10, with the labels that each got.

#263 Save integration test artifacts
  .github/workflows/all_solutions.yml
Labels: enhancement, testing

#271 Updates build_profiler.sh to explicitly fail on errors
  src/Agent/NewRelic/Profiler/linux/build_profiler.sh
Labels: bug

#273 Fixes the test results publishing issue with re-running a workflow
  .github/workflows/all_solutions.yml
Labels: bug

#272 Fixes the problem of home folders not using profiler built during workflow run
  .github/workflows/all_solutions.yml
Labels: bug, enhancement

#277 Ignore flickering test until next month
  tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
Labels: testing

#284 remove unnecessary confusing env vars
  tests/Agent/IntegrationTests/UnboundedServices/linux/docker-compose.yml
  tests/Agent/IntegrationTests/UnboundedServices/linux/mssql/Dockerfile
Labels: testing

#300 Gather additional data and consolidate integration test results
  .github/workflows/all_solutions.yml
Labels: testing

#302 adds aiohttp install in yml
  .github/workflows/all_solutions.yml
Labels: testing

#308 Integration Tests - Fix faulty logic in error event parsing from log files
  tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs
  tests/Agent/IntegrationTests/IntegrationTests/Api/AgentApiTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/AspNetCore/AspNetCoreGenericWebHostTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/AspNetCore/AspNetCoreMvcBasicRequestsTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/CSP/HighSecurityAndCustomAttributes.cs
  tests/Agent/IntegrationTests/IntegrationTests/CSP/HighSecurityModeDisabled.cs
  tests/Agent/IntegrationTests/IntegrationTests/CSP/HighSecurityModeEnabled.cs
  tests/Agent/IntegrationTests/IntegrationTests/CSP/HighSecurityModeNoTransactionAgentApiTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/CSP/SecurityPoliciesMostRestrictiveAndCustomAttributesTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/CSP/SecurityPoliciesMostRestrictiveTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/CustomAttributes/CustomAttributesIgnored.cs
  tests/Agent/IntegrationTests/IntegrationTests/CustomAttributes/CustomAttributesWebApi.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/InitiateDTAttributesTest.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/ReceiveDTAttributesTest.cs
  tests/Agent/IntegrationTests/IntegrationTests/Errors/ErrorTraceMvc.cs
  tests/Agent/IntegrationTests/IntegrationTests/Errors/ErrorTraceWebApi.cs
  tests/Agent/IntegrationTests/IntegrationTests/Errors/ErrorTraceWebService.cs
  tests/Agent/IntegrationTests/IntegrationTests/Errors/ExpectedErrorTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/Owin/OwinMiddlewareExceptionTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/Owin/OwinWebApiAsyncTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFLogHelpers.cs
Labels: testing

#316 Add back combined artifacts
  .github/workflows/all_solutions.yml
Labels: testing

#310 Fixes fail to parse expected status codes server config.
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/ServerConfiguration.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/ServerConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs
Labels: bug

#311 Integration Tests - fix broken retry logic
  .github/workflows/all_solutions.yml
  tests/Agent/IntegrationTests/Applications/AspNetCoreDistTracingApplication/Controllers/FirstCallController.cs
  tests/Agent/IntegrationTests/Applications/AspNetCoreDistTracingApplication/Controllers/SecondCallController.cs
  tests/Agent/IntegrationTests/Applications/BasicMvcApplication/Controllers/DefaultController.cs
  tests/Agent/IntegrationTests/Applications/Owin4WebApi/Controllers/DistributedTracingSenderController.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplication.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplicationFixture.cs
  tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/GetBrowserTimingHeaderAutoOn.cs
  tests/Agent/IntegrationTests/IntegrationTests/BasicInstrumentation/BasicAspWebService.cs
  tests/Agent/IntegrationTests/IntegrationTests/DataTransmission/ConnectResponseHandlingTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/W3CInstrumentationTests/HttpClientW3CTestsNetCore.cs
  tests/Agent/IntegrationTests/IntegrationTests/HttpClientInstrumentation/NetFramework/HttpClientInstrumentationNetFramework.cs
  tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AspNetCoreDistTraceRequestChainFixture.cs
  tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/BasicMvcApplicationTestFixture.cs
  tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/MockNewRelicFixture.cs
  tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/OwinWebApiFixture.cs
Labels: bug, testing

#323 Removes some prework that got committed.
  .github/workflows/all_solutions.yml
Labels: chore

#336 Deployment mainyaml
  .github/workflows/all_solutions.yml
Labels: enhancement
