Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2020-08, with the labels that each got.

#84 Adds integration tests for expected errors
  tests/Agent/IntegrationTests/Applications/AspNetCoreMvcBasicRequestsApplication/Controllers/ExpectedErrorTestController.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs
  tests/Agent/IntegrationTests/IntegrationTests/ExpectedErrorTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AspNetCoreMvcBasicRequestsFixture.cs
Labels: enhancement

#90 Add the configuration of distributed tracing to agent settings reported to New Relic
  src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs
  tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs
Labels: enhancement

#89 Add new overloading public api calls to expect errors
  src/Agent/NewRelic.Api.Agent/NewRelic.cs
  src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs
  src/Agent/NewRelic/Agent/Core/Api/AgentApiImplementation.cs
  src/Agent/NewRelic/Agent/Core/Errors/ErrorService.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/IAgentApi.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/InternalApi.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorTraceMakerTests.cs
Labels: enhancement

#95 Update README.md
  README.md
Labels: documentation

#96 Refactoring ErrorData class
  src/Agent/NewRelic/Agent/Core/Errors/ErrorData.cs
  tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/CustomErrorDataTransformerTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/ErrorEventMakerTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionEventMakerTests.cs
Labels: enhancement

#100 remove tooling additions causing a conversion
  tests/Agent/IntegrationTests/Applications/BasicWebService/BasicWebService.csproj
  tests/Agent/IntegrationTests/Applications/OwinRemotingClient/OwinRemotingClient.csproj
  tests/Agent/IntegrationTests/Applications/OwinRemotingServer/OwinRemotingServer.csproj
Labels: net35

#101 RPM package will no longer overwrite newrelic.config on upgrade
  build/Linux/build/rpm/newrelic-netcore20-agent.spec
  src/Agent/CHANGELOG.md
Labels: bug

#102 Preserve newrelic.config on .deb package upgrade
  build/Linux/build/deb/build.sh
  build/Linux/build/deb/conffiles
  src/Agent/CHANGELOG.md
Labels: bug

#99 Ignore errors new configurations
  src/Agent/NewRelic/Agent/Core/Config/Configuration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/ServerConfiguration.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  tests/Agent/UnitTests/CompositeTests/TransactionTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
  tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Errors/ErrorServiceTests.cs
Labels: enhancement

#103 Ignore error logic modification to honor new configurations.
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs
  src/Agent/NewRelic/Agent/Core/Errors/ErrorService.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
  tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Errors/ErrorServiceTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerTests.cs
Labels: enhancement

#106 Fix two bugs in core installer script
  build/Packaging/CoreInstaller/installAgent.ps1
Labels: bug

#115 Update PR template to see if it's easier to deal with
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#138 Agent decrypted encrypted proxy password
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Config/Configuration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: enhancement

#146 Dockerized rabbitmq test dependencies
  tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
  tests/Agent/IntegrationTests/UnboundedServices/rabbitmq/Dockerfile
Labels: testing

#148 Add dockerized services for both MongoDB test groups
  tests/Agent/IntegrationTests/IntegrationTestHelpers/CommonUtils.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDB2_6_AsyncCursorTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDB2_6_DatabaseTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDB2_6_IndexManagerTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDB2_6_MongoCollectionTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MongoDB/MongoDB2_6_MongoQueryProviderTests.cs
  tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
  tests/Agent/IntegrationTests/UnboundedServices/mongodb32/Dockerfile
  tests/Agent/IntegrationTests/UnboundedServices/mongodb36/Dockerfile
Labels: testing

#149 Script changes for dockerized unbounded services
  build/Scripts/run-integration-tests.ps1
  tests/Agent/IntegrationTests/UnboundedServices/unbounded-services-control.ps1
Labels: testing

#153 Dockerized couchbase test dependencies
  tests/Agent/IntegrationTests/UnboundedServices/couchbase/Dockerfile
  tests/Agent/IntegrationTests/UnboundedServices/couchbase/configure-server.sh
  tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
Labels: testing

#154 Changes obscuring key environment variable name.
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: enhancement

#151 adds docker container for redis
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/StackExchangeRedisStrongNameTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/StackExchangeRedisTests.cs
  tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
  tests/Agent/IntegrationTests/UnboundedServices/redis/Dockerfile
Labels: testing
