Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2020-12, with the labels that each got.

#372 Fix agent failed to read settings from appsettings.{environment}.json
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs
Labels: bug

#374 Fix async calculation
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Segments/NoOpSegment.cs
  src/Agent/NewRelic/Agent/Core/Segments/Segment.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ISegment.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Asp35/IntegratedPipeline/ExecuteStepWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/WrapPipelineMiddleware.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Owin/OwinStartupMiddleware.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/MethodInvokerWrapper.cs
  tests/Agent/UnitTests/CompositeTests/SegmentsTests.cs
Labels: bug

#375 Use AppDomain.CurrentDomain.BaseDirectory to get path of appsettings*.json
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Configuration/AppSettingsConfigResolveWhenUsed.cs
Labels: bug

#376 Dont dispose listeners
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Samplers/GCSamplerNetCore.cs
  src/Agent/NewRelic/Agent/Core/Samplers/SampledEventListener.cs
  src/Agent/NewRelic/Agent/Core/Samplers/ThreadStatsSampler.cs
  tests/Agent/UnitTests/CompositeTests/Samplers/GcSamplerNetCoreTests.cs
Labels: bug

#378 Fixes AddCustomAttribute throws Newtonsoft.Json.JsonWriterException: Unsupported type error when used to add header values
  src/Agent/NewRelic/Agent/Core/JsonConverters/JsonSerializerHelpers.cs
  tests/Agent/UnitTests/CompositeTests/AgentApiTests.cs
  tests/Agent/UnitTests/CompositeTests/CompositeTests.csproj
Labels: bug

#391 Remove redundant RabbitMq{Legacy}ReceiveTests
  tests/Agent/IntegrationTests/IntegrationTestHelpers/RabbitMqUtils.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyReceiverHost/Program.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyReceiverHost/RabbitMqLegacyReceiverHost.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyReceiverHost/RabbitMqLegacyReceiverHost.exe.config
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyReceiverHost/app.config
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqReceiverHost/Program.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqReceiverHost/RabbitMqReceiverHost.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqReceiverHost/RabbitMqReceiverHost.exe.config
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqReceiverHost/app.config
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqReceiverHost/packages.config
  tests/Agent/IntegrationTests/UnboundedIntegrationTests.sln
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqLegacyReceiveTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqLegacyTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqReceiveTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/RabbitMqLegacyReceiverFixture.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/RabbitMqReceiverFixture.cs
Labels: testing

#392 Consolidate existing RabbitMQ tests using inheritance
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqDistributedTracingTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqLegacyDistributedTracingTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqLegacyTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/RabbitMqBasicMvcFixture.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/RabbitMqLegacyBasicMvcFixture.cs
Labels: testing

#393 Rabbitmq netstandard20
  build/ArtifactBuilder/CoreAgentComponents.cs
  src/Agent/MsiInstaller/Installer/Product.wxs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/RabbitMq.csproj
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/RabbitMqHelper.cs
Labels: enhancement

#400 Fix NuGet restore issue in GHA builds
  .github/workflows/all_solutions.yml
Labels: bug

#398 Port RabbitMQ integration tests to use ConsoleMultiFunction test apps
  tests/Agent/IntegrationTests/IntegrationTestHelpers/IntegrationTestHelpers.csproj
  tests/Agent/IntegrationTests/IntegrationTestHelpers/RabbitMqUtils.cs
  tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/ConfigBuilderDeadlock.cs
  tests/Agent/IntegrationTests/IntegrationTests/AgentMetrics/DotNetPerfMetricsTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/Api/ApiCallsTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/BasicInstrumentation/NetStandardLibraryInstrumentation.cs
  tests/Agent/IntegrationTests/IntegrationTests/DataTransmission/FasterEventHarvestTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/W3CInstrumentationTests/W3CValidation.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFClientTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFClientTests_IISHosted.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFClientTests_SelfHosted.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFLogHelpers.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFServiceTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFServiceTests_IISHosted.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFServiceTests_SelfHosted.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFTestBase.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/ConsoleDynamicMethodFixture.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RabbitMQ.cs
  tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationCore/ConsoleMultiFunctionApplicationCore.csproj
  tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationFW/ConsoleMultiFunctionApplicationFW.csproj
  tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationFW/NetFrameworkLibraries/ConfigBuilderDeadlock.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqBasicMvcApplication/App_Start/FilterConfig.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqBasicMvcApplication/App_Start/RouteConfig.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqBasicMvcApplication/Controllers/RabbitMQController.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqBasicMvcApplication/Global.asax
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqBasicMvcApplication/Global.asax.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqBasicMvcApplication/Properties/AssemblyInfo.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqBasicMvcApplication/Properties/PublishProfiles/LocalDeploy.pubxml
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqBasicMvcApplication/RabbitMqBasicMvcApplication.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqBasicMvcApplication/Web.Debug.config
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqBasicMvcApplication/Web.Release.config
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqBasicMvcApplication/Web.config
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyBasicMvcApplication/App_Start/BundleConfig.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyBasicMvcApplication/App_Start/FilterConfig.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyBasicMvcApplication/App_Start/RouteConfig.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyBasicMvcApplication/Controllers/RabbitMQController.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyBasicMvcApplication/Global.asax
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyBasicMvcApplication/Global.asax.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyBasicMvcApplication/Properties/AssemblyInfo.cs
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyBasicMvcApplication/Properties/PublishProfiles/LocalDeploy.pubxml
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyBasicMvcApplication/RabbitMqLegacyBasicMvcApplication.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/RabbitMqLegacyBasicMvcApplication/Web.config
  tests/Agent/IntegrationTests/UnboundedIntegrationTests.sln
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqDistributedTracingTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqW3cTracingTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/RabbitMqBasicMvcFixture.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj
Labels: testing
