Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2020-07, with the labels that each got.

#19 DOTNET-4768 Comments out integration tests
  Build/Scripts/DotNet-Agent-CI-Build.ps1
  Tests/UnitTests/Core.UnitTest/NewRelic.Agent.Core.FromLegacy/AgentLoggerTest.cs
Labels: net35

#42 Script prework breakout installer
  .gitignore
  build/ArtifactBuilder/ArtifactBuilder.sln
  build/ArtifactBuilder/Artifacts/MsiInstaller.cs
  build/Scripts/DotNet-Agent-CI-Build.ps1
  src/Agent/FullAgent.sln
  src/Agent/Installer/Installer.v2.ncrunchproject
  src/Agent/InstallerActions/InstallerActions.ncrunchproject
  src/Agent/InstallerActions/InstallerActions.v2.ncrunchproject
  src/Agent/MsiInstaller/Installer/Installer.wixproj
  src/Agent/MsiInstaller/Installer/Installer.wixproj.user
  src/Agent/MsiInstaller/Installer/LicenseKeyDialog.wxs
  src/Agent/MsiInstaller/Installer/Product.wxs
  src/Agent/MsiInstaller/Installer/WizardUI.wxs
  src/Agent/MsiInstaller/Installer/packages.config
  src/Agent/MsiInstaller/Installer/ui-banner.bmp
  src/Agent/MsiInstaller/Installer/ui-banner.png
  src/Agent/MsiInstaller/Installer/ui-dialog.bmp
  src/Agent/MsiInstaller/Installer/ui-dialog.png
  src/Agent/MsiInstaller/InstallerActions/CustomAction.config
  src/Agent/MsiInstaller/InstallerActions/CustomActions.cs
  src/Agent/MsiInstaller/InstallerActions/InstallerActions.csproj
  src/Agent/MsiInstaller/InstallerActions/Properties/AssemblyInfo.cs
  src/Agent/MsiInstaller/InstallerActions/packages.config
  src/Agent/MsiInstaller/MsiInstaller.sln
Labels: net35

#38 Introduces configurations for expected error
  src/Agent/NewRelic/Agent/Core/Config/Configuration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/ServerConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: enhancement

#43 Dotnet 4737 remove todos fixmes
  src/Agent/NewRelic/Agent/Core/Aggregators/ErrorTraceAggregator.cs
  src/Agent/NewRelic/Agent/Core/Config/ConfigurationLoader.cs
  src/Agent/NewRelic/Agent/Core/Config/ConfigurationParser.cs
  src/Agent/NewRelic/Agent/Core/Configuration/ConfigurationService.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/DataTransportService.cs
  src/Agent/NewRelic/Agent/Core/Metrics/MetricNameService.cs
  src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Utils/StackTraces.cs
  src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/Agent.cs
  src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core/Environment.cs
  src/Agent/NewRelic/Agent/Core/Utilities/HeaderEncoder.cs
  src/Agent/NewRelic/Agent/Core/Utilities/IEnumerableExtensions.cs
  src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs
  src/Agent/NewRelic/Agent/Core/Wrapper/AgentWrapperApi/AgentWrapperApi.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Asp35/Shared/HttpContextActions.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/InvokeActionMethodAsyncWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/CustomInstrumentationAsync/CustomSegmentWrapperAsync.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Sql/OdbcCommandWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Sql/OleDbCommandWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Sql/SqlCommandWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/SqlAsync/PostgresCommandWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/SqlAsync/SqlCommandWrapper.cs
  src/Agent/NewRelic/Agent/LabelsService/LabelsService.cs
  src/Agent/NewRelic/Agent/NewRelic.Core/NewRelic.Reflection/Core/VisibilityBypasser.cs
  src/Agent/NewRelic/Agent/NewRelic.Core/NewRelic.Reflection/VisibilityBypasserBase.cs
  src/Agent/NewRelic/Agent/NewRelic.Core/NewRelic.SystemInterfaces/Web/Core/HttpRuntimeStatic.cs
  src/Agent/NewRelic/Agent/Parsing/SqlParser.cs
  src/Agent/NewRelic/Installer/New Relic Home Builder/Program.cs
  tests/UnitTests/CompositeTests/CompositeTests.csproj
  tests/UnitTests/CompositeTests/todo.txt
  tests/UnitTests/Core.UnitTest/Commands/CommandServiceTests.cs
  tests/UnitTests/Core.UnitTest/Database/SqlParsingCrossAgentTestJson.cs
  tests/UnitTests/Core.UnitTest/NewRelic.Agent.Core.Config.FromLegacy/ConfigurationParserTest.cs
  tests/UnitTests/Core.UnitTest/NewRelic.Agent.Core.FromLegacy/AgentStateTest.cs
  tests/UnitTests/Core.UnitTest/NewRelic.Agent.Core.Utils.Fromlegacy/StackTracesTest.cs
  tests/UnitTests/Core.UnitTest/ThreadProfiling.FromLegacy/ThreadProfilingServiceTest.cs
  tests/UnitTests/Core.UnitTest/Transactions/SyntheticsModelTests.cs
  tests/UnitTests/ParsingTests/SqlParserTests.cs
Labels: net35

#39 Add changelog for net35/main (6.x)
  src/Agent/CHANGELOG.md
Labels: documentation, net35

#44 Error collector enabled setting updates
  src/Agent/NewRelic/Agent/Core/Errors/ErrorService.cs
  src/Agent/NewRelic/Agent/Core/Segments/Segment.cs
  src/Agent/NewRelic/Agent/Core/Spans/SpanEventMaker.cs
  src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionAttributeMaker.cs
  src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionTransformer.cs
  tests/Agent/UnitTests/Core.UnitTest/Errors/ErrorServiceTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transactions/ImmutableTransactionBuilder.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionEventMakerTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerTests.cs
Labels: bug

#45 Combines ExpectedStatusCodes property into ExpectedErrorsInfo
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: enhancement

#48 Sending up the derived expected error configuration to New Relic.
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
  tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs
Labels: enhancement

#52 Add ROADMAP.md
  ROADMAP.md
Labels: documentation

#57 fix test
  tests/Agent/IntegrationTests/IntegrationTests/CatInbound/CatEnabledWithServerRedirect.cs
Labels: net35

#61 uncomment previously failing tests
  tests/Agent/UnitTests/Core.UnitTest/NewRelic.Agent.Core.FromLegacy/AgentLoggerTest.cs
Labels: net35

#55 Expected error classes and error messages implementation.
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Errors/ErrorData.cs
  src/Agent/NewRelic/Agent/Core/Errors/ErrorService.cs
  src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs
  src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionTransformer.cs
  src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Errors/ErrorServiceTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TestTransactions.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerTests.cs
Labels: enhancement

#62 Garbage Collection Performance Counters Fixes
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Samplers/GcSampler.cs
  src/NewRelic.Core/NewRelic.SystemInterfaces/IProcess.cs
  src/NewRelic.Core/NewRelic.SystemInterfaces/PerformanceCounterProxy.cs
  tests/Agent/UnitTests/CompositeTests/Samplers/GcSamplerTests.cs
  tests/NewRelic.Core.Tests/NewRelic.SystemInterfaces/PerformanceCounterProxyFactoryTests.cs
Labels: bug

#69 Generates `error.expected` attribute for Error Event, Error Trace and Span Event
  src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs
  src/Agent/NewRelic/Agent/Core/Segments/Segment.cs
  src/Agent/NewRelic/Agent/Core/Spans/SpanEventMaker.cs
  src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionAttributeMaker.cs
  tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
Labels: enhancement

#67 Ilrepack backport
  build/ArtifactBuilder/AgentComponents.cs
  build/ArtifactBuilder/FrameworkAgentComponents.cs
  src/Agent/Miscellaneous/License.txt
  src/Agent/MsiInstaller/Installer/Product.wxs
  src/Agent/NewRelic/Agent/Core/Core.csproj
  src/Agent/NewRelic/Agent/Core/Properties/Resources.Designer.cs
  src/Agent/NewRelic/Agent/NewRelic.Core/NewRelic.Core.csproj
  src/Agent/NewRelic/Installer/New Relic Home Builder/New Relic Home Builder.csproj
  src/Agent/NewRelic/Installer/New Relic Home Builder/Program.cs
Labels: net35

#71 Fixes the expectedStatusCodes configuration
  src/Agent/NewRelic/Agent/Core/Config/Configuration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/ServerConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: bug

#74 Dotnet 4774 build scripts
  .gitignore
  FullAgent.sln
  build/ArtifactBuilder/FrameworkAgentComponents.cs
  build/RepackAssemblies/Program.cs
  build/Scripts/DotNet-Agent-CI-Build.ps1
  build/Tools/vswhere.exe
  build/build.ps1
  build/build_functions.ps1
  build/build_home.ps1
  src/Agent/MsiInstaller/Installer/Product.wxs
  src/Agent/NewRelic/Agent/Extensions/Providers/CallStack/AsyncLocal/AsyncLocal.v2.ncrunchproject
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/AsyncProviders/AsyncProviders.csproj
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/AsyncProviders/AsyncTransactionContext.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/AsyncProviders/AsyncTransactionContextFactory.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/AsyncProviders/MarshalByRefImmutableStack.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/CallStack.AsyncLocal/AsyncLocal.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/CallStack.AsyncLocal/AsyncLocal.csproj
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/CallStack.AsyncLocal/CallContextStorage.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/CallStack.AsyncLocal/CallContextStorageBase.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/CallStack.AsyncLocal/CallContextStorageFactory.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/CallStack.AsyncLocal/CallContextWrappedStorage.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/CallStack.AsyncLocal/SerializeAsEmptyContainer.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/CallStack.AsyncLocal/readme.md
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/TransactionContext.Asp/Asp.csproj
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/TransactionContext.Asp/AspTransactionContext.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/TransactionContext.Asp/AspTransactionContextFactory.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/TransactionContext.Wcf3/Wcf3.csproj
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/TransactionContext.Wcf3/Wcf3OperationContextExtension.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/TransactionContext.Wcf3/Wcf3TransactionContext.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Storage/TransactionContext.Wcf3/Wcf3TransactionContextFactory.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/TransactionContext/Asp/Asp.v2.ncrunchproject
  src/Agent/NewRelic/Agent/Extensions/Providers/TransactionContext/Wcf3/Wcf3.v2.ncrunchproject
  src/Agent/NewRelic/Home/Home.csproj
  src/Agent/NewRelic/Home/README.md
  src/Agent/NewRelic/Installer/New Relic Home Builder/New Relic Home Builder.csproj
  src/Agent/NewRelic/Installer/New Relic Home Builder/New Relic Home Builder.v2.ncrunchproject
  src/Agent/NewRelic/Installer/New Relic Home Builder/Program.cs
  src/Agent/NewRelic/Installer/New Relic Home Builder/Properties/AssemblyInfo.cs
  src/Agent/NewRelic/Installer/New Relic Home Builder/packages.config
  tests/Agent/IntegrationTests/IntegrationTestHelpers/RemoteServiceFixtures/RemoteApplication.cs
  tests/Agent/UnitTests/AsyncLocalTests/AsyncLocalTests.csproj
  tests/Agent/UnitTests/AsyncLocalTests/CallStackTrackerTests.cs
  tests/Agent/UnitTests/AsyncLocalTests/MarshalByRefContainerTests.cs
Labels: net35

#73 Add/update license in nuspec files to be Apache-2.0
  build/Packaging/NugetAgentApi/NewRelic.Agent.Api.nuspec
  build/Packaging/NugetAzureCloudServices/NewRelicWindowsAzure.nuspec
  build/Packaging/NugetAzureWebSites-x64/NewRelic.Azure.WebSites.x64.nuspec
  build/Packaging/NugetAzureWebSites-x86/NewRelic.Azure.WebSites.nuspec
  build/Packaging/ScriptableInstaller/NewRelic.Net.Agent.nuspec
  build/Packaging/ScriptableInstaller/NewRelic.Net.Agent.x64.nuspec
Labels: net35

#68 Dotnet 4775 docs
  docs/development.md
  docs/integration-tests.md
Labels: net35

#72 Add repository documentation for net35 branch
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  src/Agent/CHANGELOG.md
Labels: net35

#77 Expected status code parser
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/MatchRule.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: enhancement

#76 Update package.ps1 to match main agent and fix issue
  build/ArtifactBuilder/AgentComponents.cs
  build/ArtifactBuilder/Artifacts/Artifact.cs
  build/ArtifactBuilder/Artifacts/DowloadSiteArtifact.cs
  build/ArtifactBuilder/Artifacts/MsiInstaller.cs
  build/ArtifactBuilder/Artifacts/NugetAgentApi.cs
  build/ArtifactBuilder/Artifacts/NugetAzureCloudServices.cs
  build/ArtifactBuilder/Artifacts/NugetAzureWebSites.cs
  build/ArtifactBuilder/Artifacts/ScriptableInstaller.cs
  build/ArtifactBuilder/Artifacts/ZipArchive.cs
  build/ArtifactBuilder/FileHelpers.cs
  build/ArtifactBuilder/FrameworkAgentComponents.cs
  build/ArtifactBuilder/NuGetHelpers.cs
  build/ArtifactBuilder/Program.cs
  build/package.ps1
Labels: net35

#79 Mark error data as expected if response status code is listed as expected
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Errors/ErrorService.cs
  tests/Agent/UnitTests/Core.UnitTest/Errors/ErrorServiceTests.cs
Labels: enhancement

#78 Adds back xsd2code with doc on running it
  build/Tools/xsd2code/README.md
  build/Tools/xsd2code/Xsd2Code.Library.dll
  build/Tools/xsd2code/Xsd2Code.exe
  build/Tools/xsd2code/Xsd2Code.exe.config
Labels: net35

#82 Migrate Newrelic.Core.Tests to new project format
  tests/Agent/UnitTests/NewRelic.Core.Tests/NewRelic.Core.Tests.csproj
  tests/Agent/UnitTests/NewRelic.Core.Tests/Properties/AssemblyInfo.cs
  tests/Agent/UnitTests/NewRelic.Core.Tests/packages.config
Labels: net35
