Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2020-11, with the labels that each got.

#338 Remove is metric name allowed
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Metrics/MetricNameService.cs
Labels: bug

#340 Package rpm (without GPG signing) and make available to artifactbuilder
  .github/workflows/all_solutions.yml
  build/Linux/build/rpm/build.sh
  build/Linux/docker-compose.yml
Labels: enhancement, testing

#339 tid is not always a digit
  tests/Agent/IntegrationTests/IntegrationTestHelpers/AgentLogBase.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresExecuteScalarCoreTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/Postgres/PostgresExecuteScalarTests.cs
Labels: testing

#346 Use Base64 to store key in secrets and then recreate the key as needed.
  .github/workflows/all_solutions.yml
Labels: enhancement

#344 Add the PFX for code signing into the workflow and remove self-signing
  .github/workflows/all_solutions.yml
Labels: enhancement

#348 Guard code in api stub methods
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic.Api.Agent/NewRelic.cs
Labels: bug

#349 Deployment workflow
  .github/workflows/all_solutions.yml
  .github/workflows/deploy.yml
  build/Linux/build/deb/build.sh
  build/Linux/build/rpm/build.sh
  build/Linux/docker-compose.yml
  deploy/linux/README.md
  deploy/linux/container/Dockerfile
  deploy/linux/deploy.bash
  deploy/linux/deploy_scripts/conf/apt-generate-config.in
  deploy/linux/deploy_scripts/conf/apt-release-config.in
  deploy/linux/deploy_scripts/conf/generate-testing.conf
  deploy/linux/deploy_scripts/conf/generate.conf
  deploy/linux/deploy_scripts/conf/release-testing.conf
  deploy/linux/deploy_scripts/conf/release.conf
  deploy/linux/deploy_scripts/deploy-packages.bash
  deploy/linux/deploy_scripts/lib/common.bash
  deploy/linux/deploy_scripts/libexec/colorize-changes.sed
  deploy/linux/deploy_scripts/libexec/itemize-rsync.sed
  deploy/linux/deploy_scripts/libexec/jenkins-build.bash
  deploy/linux/deploy_scripts/libexec/jenkins-download.bash
  deploy/linux/deploy_scripts/libexec/repoman-archive.bash
  deploy/linux/deploy_scripts/libexec/repoman-demote.bash
  deploy/linux/deploy_scripts/libexec/repoman-path.bash
  deploy/linux/deploy_scripts/libexec/repoman-promote.bash
  deploy/linux/deploy_scripts/libexec/repoman-rebuild.bash
  deploy/linux/deploy_scripts/libexec/s3-pull.bash
  deploy/linux/deploy_scripts/libexec/s3-push.bash
  deploy/linux/deploy_scripts/lint.bash
  deploy/linux/deploy_scripts/puppet/manifests/site.pp
  deploy/linux/deploy_scripts/puppet/modules/timezone/manifests/init.pp
  deploy/linux/deploy_scripts/puppet/modules/timezone/manifests/params.pp
  deploy/linux/deploy_scripts/rollback.bash
  deploy/linux/deploy_scripts/s3-index/.editorconfig
  deploy/linux/deploy_scripts/s3-index/.gitignore
  deploy/linux/deploy_scripts/s3-index/Makefile
  deploy/linux/deploy_scripts/s3-index/README.md
  deploy/linux/deploy_scripts/s3-index/src/indexer/main.go
  deploy/linux/deploy_scripts/s3-index/src/s3/indexer/directory.go
  deploy/linux/deploy_scripts/s3-index/src/s3/indexer/file.go
  deploy/linux/deploy_scripts/s3-index/src/s3/indexer/template.go
  deploy/linux/docker-compose.yml
  deploy/linux/packages/.gitignore
  deploy/linux/s3/production/.gitignore
  deploy/linux/s3/testing/.gitignore
Labels: enhancement

#351 8.35 release CHANGELOG updates
  src/Agent/CHANGELOG.md
Labels: documentation

#352 Deploy fixes
  .github/workflows/deploy.yml
  deploy/linux/docker-compose.yml
Labels: bug

#353 dos2unix all files for container
  .github/workflows/deploy.yml
Labels: bug

#354 Downloadsite deploy fixes
  .github/workflows/deploy.yml
Labels: bug

#356 Remove profile from download site push
  .github/workflows/deploy.yml
Labels: bug

#357 Use different secrets for Linux deploy
  .github/workflows/deploy.yml
Labels: bug

#364 Enable httpclient 5 test
  .github/workflows/all_solutions.yml
  src/Agent/CHANGELOG.md
  tests/Agent/IntegrationTests/IntegrationTests.sln
  tests/Agent/IntegrationTests/IntegrationTests/HttpClientInstrumentation/NetCore/HttpClientInstrumentationNet5.cs
Labels: enhancement

#360 Output checksum table in markdown for release notes
  .gitignore
  build/ArtifactBuilder/Artifacts/DownloadSiteArtifact.cs
Labels: enhancement

#368 - Add back self-signed cert step
  .github/workflows/all_solutions.yml
Labels: bug

#367 build.ps1 should build linux packages with or without the RPM signing key
  build/build.ps1
Labels: enhancement

#369 Update or replace actions that use now disabled methods
  .github/workflows/all_solutions.yml
Labels: chore

#371 Restore using msbuild
  .github/workflows/all_solutions.yml
  build/build.ps1
  src/Agent/NewRelic/Profiler/build/build.ps1
Labels: bug

#370 SQL parsing: ignore leading SET statements
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Parsing/SqlParser.cs
  tests/Agent/UnitTests/ParsingTests/SqlParserTests.cs
Labels: bug
