Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2021-08, with the labels that each got.

#676 Bad file name agent-version to agent_version
  .github/workflows/multiverse_run.yml
Labels: bug

#678 Update config docs link in default config
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  docs/integration-tests.md
  src/Agent/CHANGELOG.md
  src/Agent/Configuration/newrelic.config
Labels: bug, documentation

#690 Sort versions from newest to oldest
  tests/Agent/MultiverseTesting/ReportBuilder/HtmlMaker.cs
  tests/Agent/MultiverseTesting/ReportBuilder/VersionComparer.cs
Labels: enhancement

#693 Update source of MS SQL Server docker image
  tests/Agent/IntegrationTests/UnboundedServices/mssql/Dockerfile
Labels: bug

#692 Remove CacheStatsReporter
  src/Agent/NewRelic/Agent/Core/AgentHealth/CacheStatsReporter.cs
  src/Agent/NewRelic/Agent/Core/Database/CacheByDatastoreVendor.cs
  src/Agent/NewRelic/Agent/Core/Database/DatabaseService.cs
  src/Agent/NewRelic/Agent/Core/DependencyInjection/AgentServices.cs
  src/Agent/NewRelic/Agent/Core/Wrapper/AgentWrapperApi/Builders/DatabaseStatementParser.cs
  tests/Agent/Benchmarking/BenchmarkingTests/Tests/ExampleTests.cs
  tests/Agent/UnitTests/CompositeTests/SqlParsingCacheSupportabilityMetricTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Database/DatabaseService.cs
  tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/DatastoreSegmentTransformerTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TestTransactions.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerSqlTraceTests.cs
  tests/Agent/UnitTests/Core.UnitTest/WireModels/SqlTraceWireModelTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/Builders/DatabaseStatementParserTest.cs
  tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/Builders/TransactionTests.cs
Labels: enhancement

#700 Update default config to use DT over CAT
  src/Agent/Configuration/newrelic.config
  tests/Agent/IntegrationTests/IntegrationTests/CatInbound/CatDisabledHeaderPresent.cs
  tests/Agent/IntegrationTests/IntegrationTests/CatInbound/CatEnabledHeaderMissing.cs
  tests/Agent/IntegrationTests/IntegrationTests/CatInbound/CatEnabledHeaderPresentDistributedTraceSettingAbsent.cs
  tests/Agent/IntegrationTests/IntegrationTests/CatInbound/CatEnabledHeaderPresentDistributedTraceSettingFalse.cs
  tests/Agent/IntegrationTests/IntegrationTests/CatInbound/CatEnabledHeaderPresentDistributedTraceSettingTrue.cs
  tests/Agent/IntegrationTests/IntegrationTests/CatInbound/CatEnabledWithFullInboundHeaders.cs
  tests/Agent/IntegrationTests/IntegrationTests/CatInbound/CatEnabledWithServerRedirect.cs
  tests/Agent/IntegrationTests/IntegrationTests/CatInbound/CatEnabledWithUntrustedAccountId.cs
  tests/Agent/IntegrationTests/IntegrationTests/CatOutbound/CatDisabledChainedRequests.cs
  tests/Agent/IntegrationTests/IntegrationTests/CatOutbound/CatEnabledChainedAsyncAwaitRestSharp.cs
  tests/Agent/IntegrationTests/IntegrationTests/CatOutbound/CatEnabledChainedRequests.cs
  tests/Agent/IntegrationTests/IntegrationTests/CatOutbound/CatEnabledChainedRequestsHttpClient.cs
  tests/Agent/IntegrationTests/IntegrationTests/CatOutbound/CatEnabledChainedTaskResultRestSharp.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/DTSupportabilityMetricTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/DtApiTestBase.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/InitiateDTAttributesTest.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/ReceiveDTAttributesTest.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/SpanEventsAreCreatedAttributesTest.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/SpanEventsNotCreatedAttributesTest.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/W3CInstrumentationTests/TraceIdTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/W3CInstrumentationTests/W3CTestBase.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/W3CInstrumentationTests/W3CValidation.cs
  tests/Agent/IntegrationTests/IntegrationTests/RestSharp/RestSharpClientInstrumentationAsyncAwaitCAT.cs
  tests/Agent/IntegrationTests/IntegrationTests/RestSharp/RestSharpClientInstrumentationCAT.cs
  tests/Agent/IntegrationTests/IntegrationTests/RestSharp/RestSharpClientInstrumentationDistributedTracing.cs
  tests/Agent/IntegrationTests/IntegrationTests/RestSharp/RestSharpClientInstrumentationTaskResultCAT.cs
Labels: enhancement

#701 Make maximum Span Events configurable, and use new cycle and maximums sent from server
  src/Agent/CHANGELOG.md
  src/Agent/Configuration/newrelic.config
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/ServerConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/SingleEventHarvestConfig.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: enhancement
