Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2021-12, with the labels that each got.

#828 Moves MVS to run on linux in GHA
  .github/workflows/multiverse_run.yml
  tests/Agent/MultiverseTesting/ConsoleScanner/NugetClient.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/Program.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
  tests/Agent/MultiverseTesting/ReportBuilder/HtmlMaker.cs
Labels: bug

#829 Publishing fixed for MVS
  .github/workflows/multiverse_run.yml
Labels: bug

#830 Adds NServiceBus 6/7 message receive instrumentation.
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Providers/Wrapper/Delegates.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/Instrumentation.xml
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/LoadHandlersConnectorWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/NServiceBus.csproj
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/NServiceBusHelpers.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/ReceiveMessageWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/SendMessageWrapper.cs
Labels: enhancement

#833 Migrates NServiceBus 5 tests to use ConsoleMF app
  tests/Agent/IntegrationTests/NServiceBusReceiver/NServiceBusReceiver.csproj
  tests/Agent/IntegrationTests/NServiceBusReceiver/app.config
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplication.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/NServiceBus5/ConfigurationSource.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/NServiceBus5/MessageHandler.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/NServiceBus5/NServiceBusReceiverHost.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/NServiceBus5/NServiceBusService.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/NServiceBus5/NServiceBusSetup.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/NServiceBus5/SampleNServiceBusMessage.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/NServiceBus5/SampleNServiceBusMessage2.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/RootCommands.cs
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusBasicMvcApplication/App_Start/FilterConfig.cs
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusBasicMvcApplication/App_Start/RouteConfig.cs
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusBasicMvcApplication/Controllers/MessageQueueController.cs
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusBasicMvcApplication/Global.asax
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusBasicMvcApplication/Global.asax.cs
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusBasicMvcApplication/NServiceBusBasicMvcApplication.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusBasicMvcApplication/Properties/AssemblyInfo.cs
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusBasicMvcApplication/Properties/PublishProfiles/LocalDeploy.pubxml
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusBasicMvcApplication/Web.config
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusReceiverHost/App.config
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusReceiverHost/NServiceBusReceiverHost.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusReceiverHost/Program.cs
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusReceiverHost/Properties/AssemblyInfo.cs
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusReceiverHost/packages.config
  tests/Agent/IntegrationTests/UnboundedIntegrationTests.sln
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NServiceBusReceiveTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NServiceBusTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus5/NServiceBus5ReceiveTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus5/NServiceBus5Tests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/NServiceBusBasicMvcApplicationFixture.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/NServiceBusReceiverFixture.cs
Labels: enhancement

#851 Adds NServiceBus to CoreComponents in ArtifactBuilder
  build/ArtifactBuilder/CoreAgentComponents.cs
Labels: chore

#835 Guard against agent config file schema validation errors preventing agent startup; unify framework/core behavior
  src/Agent/NewRelic/Agent/Core/Config/ConfigurationLoader.cs
  src/Agent/NewRelic/Agent/Core/Core.csproj
  src/Agent/NewRelic/Agent/Core/Properties/Resources.Designer.cs
  src/Agent/NewRelic/Agent/Core/Properties/Resources.resx
  tests/Agent/UnitTests/Core.UnitTest/Core.UnitTest.csproj
  tests/Agent/UnitTests/Core.UnitTest/NewRelic.Agent.Core.Config.FromLegacy/BootstrapConfigTest.cs
  tests/Agent/UnitTests/Core.UnitTest/NewRelic.Agent.Core.FromLegacy/AgentLoggerTest.cs
Labels: enhancement

#856 NServiceBus updates, clean up and working pass
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/LoadHandlersConnectorWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/NServiceBusHelpers.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/PipelineWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/ReceiveMessageWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NServiceBus/SendMessageWrapper.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbAsyncCmdHandlerTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbAsyncEventHandlerTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbCmdHandlerTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbEventHandlerTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbPublishTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbSendTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus/NsbThrowingHandlerTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/NServiceBus5/NServiceBus5SendTests.cs
Labels: bug, chore

#814 Add support for disabling Server-Side Configuration from the Agent.
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/ServerConfiguration.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/ServerConfiguration.cs
Labels: community

#859 Update Linux package build/test and smoke test docker containers
  .gitignore
  build/Linux/test/applications/custom_attributes/NuGet.config
  build/Linux/test/applications/custom_attributes/custom_attributes.csproj
  build/Linux/test/applications/custom_xml/NuGet.config
  build/Linux/test/applications/custom_xml/custom_xml.csproj
  build/Linux/test/applications/http_client_test/NuGet.config
  build/Linux/test/applications/http_client_test/http_client_test.csproj
  build/Linux/test/distros/centos/Dockerfile
  build/Linux/test/distros/debian/Dockerfile
  build/Linux/test/scripts/custom_attributes_test.sh
  build/Linux/test/scripts/custom_attributes_test_tarball.sh
  build/Linux/test/scripts/custom_xml_test.sh
  build/Linux/test/scripts/mvc_test.sh
  build/Linux/test/scripts/util.sh
  tests/Agent/SmokeTest/Dockerfile
  tests/Agent/SmokeTest/app/AgentSmokeTest.csproj
  tests/Agent/SmokeTest/run.sh
Labels: chore

#862 Use pipefail option in Linux package deploy scripts
  deploy/linux/Dockerfile
  deploy/linux/README.md
  deploy/linux/container/Dockerfile
  deploy/linux/deploy.bash
  deploy/linux/deploy_scripts/deploy-packages.bash
  deploy/linux/deploy_scripts/libexec/repoman-archive.bash
  deploy/linux/deploy_scripts/libexec/repoman-demote.bash
  deploy/linux/deploy_scripts/libexec/repoman-promote.bash
  deploy/linux/deploy_scripts/libexec/repoman-rebuild.bash
  deploy/linux/docker-compose.yml
Labels: Incident Action Item, technical debt
