Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2021-09, with the labels that each got.

#708 Fix bug when capturing explain plans for paramaterized SQL
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Parsing/SqlParser.cs
Labels: bug

#710 Add Castle.Monorail deprecation statement
  src/Agent/CHANGELOG.md
Labels: chore

#722 Ready v9 changelog
  src/Agent/CHANGELOG.md
Labels: chore

#723 Better unbounded service security
  tests/Agent/IntegrationTests/Shared/RabbitMqConfiguration.cs
  tests/Agent/IntegrationTests/Shared/StackExchangeRedisConfiguration.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RabbitMQ.cs
  tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Controllers/RedisController.cs
  tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
  tests/Agent/IntegrationTests/UnboundedServices/example-secrets.json
  tests/Agent/IntegrationTests/UnboundedServices/mssql/Dockerfile
  tests/Agent/IntegrationTests/UnboundedServices/rabbitmq/Dockerfile
  tests/Agent/IntegrationTests/UnboundedServices/redis/Dockerfile
Labels: testing

#727 Update changelog to mark 9.0.0 as released
  src/Agent/CHANGELOG.md
Labels: chore
