Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2021-05, with the labels that each got.

#555 Reduce integration test solution build warnings
  tests/Agent/IntegrationTests/Applications/AspNetCore3BasicWebApiApplication/AspNetCore3BasicWebApiApplication.csproj
  tests/Agent/IntegrationTests/Applications/ConsoleAsyncApplication/AsyncFireAndForgetUseCases.cs
  tests/Agent/IntegrationTests/Applications/DistributedTracingApiApplication/Program.cs
  tests/Agent/IntegrationTests/Applications/ServiceStackApplication/ServiceStackApplication.csproj
  tests/Agent/IntegrationTests/Applications/WebApiAsyncApplication/Controllers/AsyncFireAndForgetController.cs
  tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AspNetCore3BasicWebApiApplicationFixture.cs
  tests/Agent/IntegrationTests/IntegrationTests/app.config
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
  tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationCore/ConsoleMultiFunctionApplicationCore.csproj
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/app.config
Labels: testing

#568 Adds allowAllHeaders config setting.
  src/Agent/Configuration/newrelic.config
  src/Agent/NewRelic/Agent/Core/Config/Configuration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: enhancement

#569 High security mode will disable request header capturing
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: enhancement

#570 Introduces SetRequestHeaders api method
  src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs
  src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs
  src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs
  tests/Agent/UnitTests/Core.UnitTest/Attributes/AttributeDefinitionServiceTests.cs
Labels: enhancement

#572 Change SetRequestHeaders method signature.
  src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs
  src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/ITransaction.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
Labels: enhancement

#579 Fixes allowAllHeaders setting logic
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Attributes/AttributeDefinitionServiceTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
Labels: enhancement

#582 Lowercase request header attributes.
  src/Agent/Configuration/newrelic.config
  src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
Labels: enhancement

#585 Updates conditional to allow scheduled ruhns
  .github/workflows/all_solutions.yml
Labels: bug

#583 Request headers capture support for AspNetCore application.
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/WrapPipelineMiddleware.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs
  tests/Agent/IntegrationTests/IntegrationTests/RemoteServiceFixtures/AspNetCoreMvcBasicRequestsFixture.cs
  tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNetCore/AllowAllHeadersDisabledTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/RequestHeadersCapture/AspNetCore/AllowAllHeadersEnabledTests.cs
Labels: enhancement

#586 When high security mode is enabled, don't collect any request headers.
  src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionAttributeMakerTests.cs
Labels: bug
