Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2021-03, with the labels that each got.

#480 Removes nuget check from AWS Lambda
  .github/workflows/deploy_awslambda.yml
Labels: bug

#481 Lambda release fixes
  .github/workflows/all_solutions.yml
  .github/workflows/awslambda_release.yml
Labels: bug

#482 Fixed artifact builder paths to build properties
  .github/workflows/awslambda_release.yml
Labels: bug

#478 Fix azure site extension
  .github/workflows/deploy_siteextension.yml
  .github/workflows/siteextension_release.yml
  build/Packaging/AzureSiteExtension/Content/install.ps1
  src/Agent/CHANGELOG.md
Labels: bug

#487 Fixes generateBuildProperties.ps1 to work with lightweighted tags
  build/generateBuildProperties.ps1
Labels: bug

#494 Update README.md
  README.md
Labels: documentation

#493 Language independently convert float number value to string for tracestate Priority value
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/DistributedTracing/DistributedTracePayloadHandler.cs
  src/NewRelic.Core/DistributedTracing/W3CTracestate.cs
  tests/Agent/IntegrationTests/Applications/AspNetCoreMvcBasicRequestsApplication/Controllers/HomeController.cs
  tests/Agent/UnitTests/Core.UnitTest/DistributedTracing/W3CTracestateTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/DistributedTracing/DistributedTracePayloadHandlerTests.cs
Labels: bug

#508 Remove hardcoded instrumentation points in wcf wrappers.
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/ChannelFactoryWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/DispatcherBuilderWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/Instrumentation.xml
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/MethodInvokerWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/ServiceChannelProxyWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/WcfIgnoreOuterTransactionWrapper.cs
Labels: enhancement
