Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2021-01, with the labels that each got.

#423 Reverts grpc packages update due to 8T breaking
  build/build_functions.ps1
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Core.csproj
Labels: bug

#424 8t logging improvement
  src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs
Labels: enhancement

#418 Add more RabbitMQ client version/runtime combinations to RabbitMQ integration tests
  tests/Agent/IntegrationTests/IntegrationTests/AgentFeatures/ConfigBuilderDeadlock.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/ConsoleDynamicMethodFixture.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RabbitMQ.cs
  tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationFW/ConsoleMultiFunctionApplicationFW.csproj
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqDistributedTracingTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqTests.cs
Labels: testing

#429 flipped finest boolean in WCF logging
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Wcf3/MethodInvokerWrapper.cs
Labels: enhancement

#425 Infinite tracing handle failed precondition
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs
  tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
Labels: enhancement

#431 8T integration tests
  tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs
  tests/Agent/IntegrationTests/IntegrationTests/AgentMetrics/DotNetPerfMetricsTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/Api/ApiCallsTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/BasicInstrumentation/NetStandardLibraryInstrumentation.cs
  tests/Agent/IntegrationTests/IntegrationTests/DataTransmission/FasterEventHarvestTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/InfiniteTracing/InfiniteTracingTests.cs
  tests/Agent/IntegrationTests/Shared/IntegrationTestConfiguration.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/ConsoleDynamicMethodFixture.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/InfiniteTracingTester.cs
  tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationCore/ConsoleMultiFunctionApplicationCore.csproj
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqDistributedTracingTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RabbitMq/RabbitMqTests.cs
  tests/Agent/IntegrationTests/UnboundedServices/example-secrets.json
Labels: enhancement

#433 8t more failed precondition handling
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/SpanStreamingService.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
Labels: enhancement

#444 Fix nservicebus test
  tests/Agent/IntegrationTests/UnboundedApplications/NServiceBusBasicMvcApplication/Controllers/MessageQueueController.cs
Labels: testing
