Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2021-11, with the labels that each got.

#782 Improve management of gRPC channels
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/DataTransport/DataStreamingService.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/GrpcWrapper.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/SpanGrpcWrapper.cs
  tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
Labels: bug

#791 Fix dbcollection attribute.
  src/Agent/NewRelic/Agent/Core/Segments/DatastoreSegmentData.cs
  tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs
Labels: bug

#792 Refactor gcsampler log all exceptions
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Samplers/GcSampler.cs
Labels: enhancement

#793 CosmosDB container management tests
  tests/Agent/IntegrationTests/Shared/ReflectionHelpers/DynamicMethodExecutor.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/CosmosDBExerciser.cs
  tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationCore/ConsoleMultiFunctionApplicationCore.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/MongoDB2_6CoreApplication/MongoDB2_6CoreApplication.csproj
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/CosmosDB/CosmosDBTests.cs
  tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml
  tests/Agent/UnitTests/Core.UnitTest/Spans/SpanEventMakerTests.cs
Labels: enhancement

#795 Makes multiverse scanner reusable
  .github/workflows/multiverse_run.yml
Labels: bug, enhancement

#796 Updates all_solutions.yml to call MVS as a reusable workflow
  .github/workflows/all_solutions.yml
Labels: bug

#797 JamesIves/github-pages-deploy-action doesn't support base versions
  .github/workflows/multiverse_run.yml
Labels: bug

#798 Fix pathing issue in workflow
  .github/workflows/multiverse_run.yml
Labels: bug

#802 Cosmosdb item management operations tests
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/CosmosDBExerciser.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/SalesOrder.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/CosmosDB/CosmosDBTests.cs
Labels: enhancement

#809 Adds CosmosDb batch operation related tests.
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/CosmosDBExerciser.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/CosmosDB/CosmosDBTests.cs
Labels: enhancement

#810 Cosmosdb stored procedure tests
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/CosmosDBExerciser.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/CosmosDB/StoredProcedures/HelloWorldStoredProc.js
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/CosmosDB/CosmosDBTests.cs
Labels: enhancement

#812 Updates deploy.yml for fastly
  .github/workflows/deploy_agent.yml
Labels: enhancement

#813 Fixing pathing in MVS
  .github/workflows/multiverse_run.yml
Labels: bug

#816 Mvs add postgres
  .github/workflows/multiverse_run.yml
  tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
Labels: bug
