Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2021-04, with the labels that each got.

#509 Remove hardcoded instrumentation points in MongoDb wrappers.
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/BulkWriteOperationExecuteWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/Instrumentation.xml
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/MongoCollectionDefaultWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/MongoCollectionFindWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/MongoCollectionInsertWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/MongoCollectionRemoveWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/MongoCursorWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb/MongoDatabaseDefaultWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/AsyncCursorWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/Instrumentation.xml
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/MongoCollectionBaseWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/MongoCollectionImplWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/MongoDatabaseWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/MongoIndexManagerBaseWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/MongoIndexManagerWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MongoDb26/MongoQueryProviderImplWrapper.cs
Labels: enhancement

#510 Removes hard coded instrumentation points in rabbit wrappers.
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/BasicGetWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/BasicPublishWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/BasicPublishWrapperLegacy.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/HandleBasicDeliverWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/Instrumentation.xml
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/QueuePurgeWrapper.cs
Labels: enhancement

#519 Initial setup of Multiverse testing
  .github/workflows/all_solutions.yml
  tests/Agent/MultiverseTesting/ConsoleScanner/ConsoleScanner.csproj
  tests/Agent/MultiverseTesting/ConsoleScanner/InstrumentationSet.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/Program.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/Properties/launchSettings.json
  tests/Agent/MultiverseTesting/ConsoleScanner/README.md
  tests/Agent/MultiverseTesting/ConsoleScanner/ScannerConfiguration.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
  tests/Agent/MultiverseTesting/MultiverseScanner/AssemblyAnalyzer.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/ExtensionSerialization/ExactMethodMatcher.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/ExtensionSerialization/Extension.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/ExtensionSerialization/Instrumentation.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/ExtensionSerialization/Match.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/ExtensionSerialization/TracerFactory.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/InstrumentationValidator.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Models/AssemblyAnalysis.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Models/AssemblyModel.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Models/ClassModel.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Models/InstrumentationModel.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Models/MethodModel.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/MultiverseScanner.csproj
  tests/Agent/MultiverseTesting/MultiverseScanner/README.md
  tests/Agent/MultiverseTesting/MultiverseScanner/Reporting/ClassValidation.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Reporting/InstrumentationReport.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Reporting/MethodValidation.cs
  tests/Agent/MultiverseTesting/MultiverseTesting.sln
  tests/Agent/MultiverseTesting/README.md
Labels: enhancement

#524 Adds support for env vars in config.yml
  tests/Agent/MultiverseTesting/ConsoleScanner/InstrumentationSet.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/NugetSet.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/Program.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/Properties/launchSettings.json
  tests/Agent/MultiverseTesting/ConsoleScanner/README.md
  tests/Agent/MultiverseTesting/ConsoleScanner/ScannerConfiguration.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
  tests/Agent/MultiverseTesting/MultiverseScanner/README.md
  tests/Agent/MultiverseTesting/README.md
Labels: enhancement

#523 Update StackTraces.ScrubAndTruncate to handle zero max depth
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Utils/StackTraces.cs
  tests/Agent/UnitTests/Core.UnitTest/NewRelic.Agent.Core.Utils.Fromlegacy/StackTracesTest.cs
Labels: bug, on-hold

#526 Refactors the Multi Version Scanner
  tests/Agent/MultiverseTesting/ConsoleScanner/DownloadedNugetInfo.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/InstrumentationSet.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/NugetSet.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/Program.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/Properties/launchSettings.json
  tests/Agent/MultiverseTesting/ConsoleScanner/ScannerConfiguration.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
  tests/Agent/MultiverseTesting/MultiverseScanner/AssemblyAnalyzer.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/InstrumentationValidator.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Models/AssemblyAnalysis.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Models/AssemblyModel.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Reporting/InstrumentationReport.cs
Labels: enhancement

#527 Mvs replace nuget
  tests/Agent/MultiverseTesting/ConsoleScanner/ConsoleScanner.csproj
  tests/Agent/MultiverseTesting/ConsoleScanner/NugetClient.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/NugetSet.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/Program.cs
Labels: enhancement

#534 Mvs write report
  tests/Agent/MultiverseTesting/ConsoleScanner/DownloadedNugetInfo.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/NugetClient.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/Program.cs
  tests/Agent/MultiverseTesting/ConsoleScanner/Properties/launchSettings.json
  tests/Agent/MultiverseTesting/ConsoleScanner/README.md
  tests/Agent/MultiverseTesting/ConsoleScanner/config.yml
  tests/Agent/MultiverseTesting/MultiverseScanner/AssemblyAnalyzer.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Models/AssemblyModel.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Reporting/AssemblyReport.cs
  tests/Agent/MultiverseTesting/MultiverseScanner/Reporting/InstrumentationReport.cs
Labels: enhancement

#536 Adds workflow to run MultiverseScanner on schedule
  .github/workflows/multiverse_run.yml
Labels: enhancement

#538 Fixes problems with initial setup of MVS
  .github/workflows/multiverse_run.yml
Labels: bug
