Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2021-07, with the labels that each got.

#624 Add Linux package deploy test mode
  .github/workflows/deploy.yml
  deploy/linux/.gitignore
  deploy/linux/README.md
  deploy/linux/deploy.bash
  deploy/linux/deploy_scripts/deploy-packages.bash
  deploy/linux/deploy_scripts/libexec/repoman-rebuild.bash
Labels: chore

#628 Update Linux package deploy process to use Debian 10 (Buster) and gnupg1
  build/Linux/linux_packaging.md
  deploy/linux/README.md
  deploy/linux/container/Dockerfile
  deploy/linux/deploy_scripts/libexec/repoman-rebuild.bash
Labels: chore

#630 Improve sqlparsing tostring in FixParameterizedSql
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Parsing/MySqlExplainPlanActions.cs
  src/Agent/NewRelic/Agent/Parsing/SqlParser.cs
  src/Agent/NewRelic/Agent/Parsing/SqlServerExplainPlanActions.cs
  tests/Agent/UnitTests/ParsingTests/SqlParserTests.cs
Labels: bug

#636 Prevent inlining in integration test app methods
  tests/Agent/IntegrationTests/Applications/AspNetCoreMvcAsyncApplication/CustomMiddleware.cs
  tests/Agent/IntegrationTests/Applications/AspNetCoreMvcFrameworkAsyncApplication/CustomMiddleware.cs
  tests/Agent/IntegrationTests/Applications/ConsoleOtherTransactionWrapperApplication/Program.cs
  tests/Agent/IntegrationTests/Applications/DistributedTracingApiApplication/Program.cs
  tests/Agent/IntegrationTests/Applications/Owin2WebApi/CustomMiddleware.cs
  tests/Agent/IntegrationTests/Applications/Owin3WebApi/CustomMiddleware.cs
  tests/Agent/IntegrationTests/Applications/Owin4WebApi/CustomMiddleware.cs
  tests/Agent/IntegrationTests/IntegrationTests/DistributedTracing/DTSupportabilityMetricTests.cs
Labels: testing

#637 Improve integration test reliability
  tests/Agent/IntegrationTests/IntegrationTestHelpers/RandomPortGenerator.cs
  tests/Agent/IntegrationTests/IntegrationTests/WCF/WCFServiceTests.cs
Labels: testing

#647 Update DbParameterData for Oracle
  tests/Agent/IntegrationTests/Shared/DbParameterData.cs
Labels: testing

#648 RabbitMQ: Use generic IDictionary interface when manipulating headers
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/HandleBasicDeliverWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/RabbitMq/RabbitMqHelper.cs
  src/Agent/NewRelic/Profiler/README.md
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/RabbitMQ.cs
Labels: bug

#650 Disable unbounded int test job in GHA
  .github/workflows/all_solutions.yml
Labels: testing

#651 Create stack traces on every segment and send them up in transaction traces
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Config/Configuration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
  src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Utils/StackTraces.cs
  src/Agent/NewRelic/Agent/Core/Segments/Segment.cs
  tests/Agent/UnitTests/CompositeTests/SqlTraceTests.cs
  tests/Agent/UnitTests/CompositeTests/StackTraceTransactionTraceTests.cs
  tests/Agent/UnitTests/Core.UnitTest/NewRelic.Agent.Core.Utils.Fromlegacy/StackTracesTest.cs
  tests/Agent/UnitTests/Core.UnitTest/Spans/SpanStreamingServiceTests.cs
Labels: enhancement

#659 Update CHANGELOG.md
  src/Agent/CHANGELOG.md
Labels: chore
