Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2022-04, with the labels that each got.

#1045 Updates applicationLogging level to be log.level
  src/Agent/NewRelic/Agent/Core/Agent.cs
  src/Agent/NewRelic/Agent/Core/JsonConverters/LogEventWireModelCollectionJsonConverter.cs
  src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModel.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/LogData.cs
  tests/Agent/IntegrationTests/IntegrationTests/Logging/MaxSamplesStoredTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs
  tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LogEventWireModelCollectionJsonConverterTests.cs
  tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelCollectionTests.cs
  tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs
Labels: enhancement, chore

#1049 Fixes, updates,and adds NoticeError docs - removes 1000 character limit note in docs
  src/Agent/NewRelic.Api.Agent/NewRelic.cs
  src/Agent/NewRelic/Agent/Core/Api/AgentApi.cs
  src/Agent/NewRelic/Agent/Core/Api/AgentApiImplementation.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/IAgentApi.cs
Labels: bug

#1055 Add missing logging components to MSI Wix config
  src/Agent/MsiInstaller/Installer/Product.wxs
Labels: bug

#1058 error.message accepts uo to 1023 chars insread of 255 with unit tests
  src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinition.cs
  src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs
  tests/Agent/UnitTests/Core.UnitTest/Attributes/AttributeTests.cs
Labels: enhancement

#1061 Enable/disable cloud detection via environment variables
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: feature

#1065 Adds environment variables for all proxy settings
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: feature pack
