Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2022-05, with the labels that each got.

#1066 Fix fail to execute explain plan
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Parsing/SqlParser.cs
  tests/Agent/IntegrationTests/Shared/DbParameterData.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MsSql/MsSqlStoredProcedureTests.cs
Labels: bug

#1076 Serilog dupe stackframe fix
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/SerilogWrapper.cs
  tests/Agent/IntegrationTests/IntegrationTests/Logging/Common.cs
  tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/Controllers/TestController.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/LoggingTester.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/SerilogLoggingWebAdapter.cs
Labels: bug

#1078 APM Logs-in-Context Forwarding on by default
  src/Agent/NewRelic/Agent/Core/Config/Configuration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
  tests/Agent/IntegrationTests/IntegrationTests/Logging/HSMOrCSPDisablesForwardingTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/Logging/LocalDecorationTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/Logging/MaxSamplesStoredTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/Logging/ZeroMaxSamplesStoredTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: feature

#1107 Upgrade Newtonsoft.Json to 13.0.1
  build/ArtifactBuilder/ArtifactBuilder.csproj
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Core.csproj
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/WebApi1/app.config
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/WebApi2/app.config
  src/NewRelic.Core/NewRelic.Core.csproj
  tests/Agent/Benchmarking/BenchmarkingTests/BenchmarkingTests.csproj
  tests/Agent/IntegrationTests/Applications/BasicWebApplication/BasicWebApplication.csproj
  tests/Agent/IntegrationTests/Applications/BasicWebApplication/Web.config
  tests/Agent/IntegrationTests/Applications/CustomAttributesWebApi/CustomAttributesWebApi.csproj
  tests/Agent/IntegrationTests/Applications/MockNewRelic/MockNewRelic.csproj
  tests/Agent/IntegrationTests/Applications/MvcAsyncApplication/MvcAsyncApplication.csproj
  tests/Agent/IntegrationTests/Applications/MvcAsyncApplication/Web.config
  tests/Agent/IntegrationTests/Applications/Owin2WebApi/Owin2WebApi.csproj
  tests/Agent/IntegrationTests/Applications/Owin3WebApi/Owin3WebApi.csproj
  tests/Agent/IntegrationTests/Applications/Owin4WebApi/Owin4WebApi.csproj
  tests/Agent/IntegrationTests/Applications/OwinRemotingClient/App.config
  tests/Agent/IntegrationTests/Applications/OwinRemotingClient/OwinRemotingClient.csproj
  tests/Agent/IntegrationTests/Applications/OwinRemotingServer/App.config
  tests/Agent/IntegrationTests/Applications/OwinRemotingServer/OwinRemotingServer.csproj
  tests/Agent/IntegrationTests/Applications/RejitMvcApplication/RejitMvcApplication.csproj
  tests/Agent/IntegrationTests/Applications/WebApiAsyncApplication/Web.config
  tests/Agent/IntegrationTests/Applications/WebApiAsyncApplication/WebApiAsyncApplication.csproj
  tests/Agent/IntegrationTests/IntegrationTestHelpers/IntegrationTestHelpers.csproj
  tests/Agent/IntegrationTests/IntegrationTests/IntegrationTests.csproj
  tests/Agent/IntegrationTests/IntegrationTests/app.config
  tests/Agent/IntegrationTests/Models/Models.csproj
  tests/Agent/IntegrationTests/Shared/Shared.csproj
  tests/Agent/IntegrationTests/SharedApplications/ConsoleMultiFunctionApplicationFW/packages.config
  tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Web.config
  tests/Agent/IntegrationTests/UnboundedApplications/MSMQBasicMVCApplication/MSMQBasicMVCApplication.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/MSMQBasicMVCApplication/Web.config
  tests/Agent/IntegrationTests/UnboundedApplications/MongoDB2_6Application/MongoDB2_6Application.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/MongoDB2_6Application/Web.config
  tests/Agent/IntegrationTests/UnboundedApplications/MongoDBApplication/MongoDBApplication.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/MongoDBApplication/Web.config
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/app.config
  tests/Agent/PlatformTests/Applications/NetFrameworkBasicApplication/NetFrameworkBasicApplication/Web.config
  tests/Agent/PlatformTests/Applications/NetFrameworkBasicApplication/NetFrameworkBasicApplication/packages.config
  tests/Agent/PlatformTests/Applications/ServiceFabricApplication/OwinService/OwinService.csproj
  tests/Agent/UnitTests/CompositeTests/CompositeTests.csproj
  tests/Agent/UnitTests/Core.UnitTest/Core.UnitTest.csproj
Labels: chore

#1104 Adds ability to remove deprecated instrumentation files post installation
  build/Linux/build/deb/postinst
  build/Linux/build/rpm/newrelic-netcore20-agent.spec
  build/Packaging/AzureSiteExtension/Content/install.ps1
  src/Agent/CHANGELOG.md
  src/Agent/MsiInstaller/InstallerActions/CustomActions.cs
Labels: bug

#1109 Add NLogLogging extension to ArtifactBuilder
  build/ArtifactBuilder/CoreAgentComponents.cs
  build/ArtifactBuilder/FrameworkAgentComponents.cs
Labels: chore

#1111 Pin MySQL unbounded service to known working version (8.0.28)
  tests/Agent/IntegrationTests/UnboundedServices/mysql/Dockerfile
Labels: chore

#1108 Updates the Microsoft.AspNetCore.Mvc.Core reference to a safer version.
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/AspNetCore.csproj
Labels: chore
