Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2022-01, with the labels that each got.

#860 Refactoring SSC disabling logic.
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/ReportedConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/ServerConfiguration.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/ConnectionHandler.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/DataTransport/AgentSettingsTests.cs
Labels: enhancement

#866 Fix correctly report whether SSC is enabled.
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Configuration/ServerConfiguration.cs
Labels: bug

#799 allow NewRelicQueryName to be specified for SQL, with unit tests
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Parsing/SqlParser.cs
  tests/Agent/UnitTests/ParsingTests/SqlParserTests.cs
Labels: enhancement, community

#870 Automatically detect CLR type.
  src/Agent/NewRelic/Profiler/Configuration/Configuration.h
  src/Agent/NewRelic/Profiler/Logging/DefaultFileLogLocation.h
  src/Agent/NewRelic/Profiler/LoggingTest/DefaultFileLogLocationTest.cpp
  src/Agent/NewRelic/Profiler/MethodRewriter/ISystemCalls.h
  src/Agent/NewRelic/Profiler/MethodRewriterTest/MockSystemCalls.h
  src/Agent/NewRelic/Profiler/Profiler/CoreCLRCorProfilerCallbackImpl.h
  src/Agent/NewRelic/Profiler/Profiler/FrameworkCorProfilerCallbackImpl.h
  src/Agent/NewRelic/Profiler/Profiler/ICorProfilerCallbackBase.h
  src/Agent/NewRelic/Profiler/Profiler/SystemCalls.h
  src/Agent/NewRelic/Profiler/Profiler/UnixSystemCalls.h
Labels: enhancement

#879 tracepararent is a typo
  tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/DistributedTracing/DistributedTracePayloadHandlerTests.cs
Labels: community

#881 Refactoring ShouldInstrument method.
  src/Agent/NewRelic/Profiler/Configuration/Configuration.h
  src/Agent/NewRelic/Profiler/ConfigurationTest/ConfigurationTest.cpp
  src/Agent/NewRelic/Profiler/ConfigurationTest/ShouldInstrumentTest.cpp
  src/Agent/NewRelic/Profiler/Profiler/CorProfilerCallbackImpl.h
Labels: enhancement

#884 Fix broken/obsolete URLs in NuGet package metadata
  build/Packaging/NugetAgent/NewRelic.Agent.nuspec
  build/Packaging/NugetAgentApi/NewRelic.Agent.Api.nuspec
  build/Packaging/NugetAzureWebSites-x64/NewRelic.Azure.WebSites.x64.nuspec
  build/Packaging/NugetAzureWebSites-x86/NewRelic.Azure.WebSites.nuspec
Labels: bug

#890 Add Linux integration test instructions
  docs/integration-tests.md
Labels: documentation

#901 Update iconUrl in nuspec files
  build/Packaging/AzureSiteExtension/NewRelic.Azure.WebSites.Extension.nuspec
  build/Packaging/NugetAgent/NewRelic.Agent.nuspec
  build/Packaging/NugetAgentApi/NewRelic.Agent.Api.nuspec
  build/Packaging/NugetAwsLambdaOpenTracer/NewRelic.OpenTracing.AmazonLambda.Tracer.nuspec
  build/Packaging/NugetAzureCloudServices/NewRelicWindowsAzure.nuspec
  build/Packaging/NugetAzureWebSites-x64/NewRelic.Azure.WebSites.x64.nuspec
  build/Packaging/NugetAzureWebSites-x86/NewRelic.Azure.WebSites.nuspec
  build/Packaging/ScriptableInstaller/NewRelic.Net.Agent.nuspec
  build/Packaging/ScriptableInstaller/NewRelic.Net.Agent.x64.nuspec
Labels: bug
