Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2022-08, with the labels that each got.

#1204 Added support for Labels to be set from AppSettings.json or web/app.config
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
Labels: enhancement, community

#1208 Community: Added support for Labels to be set from AppSettings.json or web/app.config
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: enhancement, community

#1207 MySql.Data Unbounded Integration Test Migration to ConsoleMF
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MySql/MySqlExerciser.cs
  tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlAsyncTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlStoredProcedureTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/MySqlBasicMvcFixture.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj
Labels: testing

#1210 Update all ubuntu 18.04 runners to 22.04
  .github/workflows/all_solutions.yml
Labels: chore

#1213 Fix timing issue with RestSharpClientTaskCancelled requests
  tests/Agent/IntegrationTests/Applications/BasicMvcApplication/Controllers/RestAPIController.cs
Labels: testing

#1215 Set ExclusiveAddressUse to true in RandomPortGenerator
  tests/Agent/IntegrationTests/IntegrationTestHelpers/RandomPortGenerator.cs
Labels: bug, testing

#1224 Migrate to dotnet test for integration and Unbounded tests
  .github/workflows/all_solutions.yml
  .github/workflows/run_integration_tests.yml
  tests/Agent/IntegrationTests/IntegrationTests/IntegrationTests.csproj
  tests/Agent/IntegrationTests/IntegrationTests/xunit.runner.json
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/xunit.runner.json
Labels: technical debt

#1220 Migrates MySqlConnector tests to ConsoleMF.
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/MySql/MySqlConnectorExerciser.cs
  tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/BasicMvcApplication.csproj
  tests/Agent/IntegrationTests/UnboundedApplications/BasicMvcApplication/Controllers/MySqlConnectorController.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlConnectorTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/MySql/MySqlTests.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/RemoteServiceFixtures/MySqlConnectorBasicMvcFixture.cs
  tests/Agent/IntegrationTests/UnboundedIntegrationTests/UnboundedIntegrationTests.csproj
Labels: testing, intern
