Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2022-02, with the labels that each got.

#894 Log metrics
  .github/workflows/all_solutions.yml
  FullAgent.sln
  build/ArtifactBuilder/CoreAgentComponents.cs
  build/ArtifactBuilder/FrameworkAgentComponents.cs
  src/Agent/NewRelic/Agent/Core/Agent.cs
  src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs
  src/Agent/NewRelic/Agent/Core/AgentHealth/IAgentHealthReporter.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs
  src/Agent/NewRelic/Agent/Core/WireModels/IMetricBuilder.cs
  src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/IAgentExperimental.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Instrumentation.xml
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Logging.csproj
  tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs
  tests/Agent/IntegrationTests/IntegrationTests/AgentLogs/ChangeLogDirectoryTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/AgentLogs/ChangeLogFilenameTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/AgentLogs/LogLevelAndDirectoryEnvironmentTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/AgentLogs/LogLevelInfoAndAuditLogFalseTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/AgentLogs/LogLevelInfoAndAuditLogNotSetTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/AgentLogs/LogLevelInfoAndAuditLogTrueTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/AgentLogs/LogLevelOffAndAuditLogTrueTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/Logging/Log4netMetricsTests.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/MultiFunctionApplicationHelpers.csproj
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/Log4netTester.cs
  tests/Agent/UnitTests/Core.UnitTest/AgentHealth/AgentHealthReporterTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: feature

#913 Adds configuration for log forwarding
  src/Agent/NewRelic/Agent/Core/Config/Configuration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Configuration/EventHarvestConfig.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: feature

#920 Adds RecordLogMessage and LogEvents to Transaction with tests
  src/Agent/NewRelic/Agent/Core/Transactions/IInternalTransaction.cs
  src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs
  src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/ITransactionExperimental.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Instrumentation.xml
  tests/Agent/UnitTests/Core.UnitTest/Transactions/TransactionTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TestTransactions.cs
Labels: feature

#923 Update log4net wrapper to call RecordLogMessage
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs
Labels: feature

#926 Adds LogEventAggregator with supportability metrics and tests
  src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs
  src/Agent/NewRelic/Agent/Core/AgentHealth/IAgentHealthReporter.cs
  src/Agent/NewRelic/Agent/Core/Aggregators/LogEventAggregator.cs
  src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs
  src/Agent/NewRelic/Agent/Core/WireModels/IMetricBuilder.cs
  src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs
  tests/Agent/UnitTests/Core.UnitTest/AgentHealth/AgentHealthReporterTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Aggregators/LogEventAggregatorTests.cs
Labels: feature

#899 Data Usage Supportability Metrics
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs
  src/Agent/NewRelic/Agent/Core/AgentHealth/DestinationInteractionSample.cs
  src/Agent/NewRelic/Agent/Core/AgentHealth/IAgentHealthReporter.cs
  src/Agent/NewRelic/Agent/Core/DataTransport/HttpCollectorWire.cs
  src/Agent/NewRelic/Agent/Core/NewRelic.Agent.Core.Metric/MetricNames.cs
  src/Agent/NewRelic/Agent/Core/WireModels/IMetricBuilder.cs
  src/Agent/NewRelic/Agent/Core/WireModels/MetricDataWireModel.cs
  src/Agent/NewRelic/Agent/Core/WireModels/MetricWireModel.cs
  tests/Agent/IntegrationTests/IntegrationTests/AgentMetrics/DataUsageSupportabilityMetricsTests.cs
  tests/Agent/UnitTests/Core.UnitTest/AgentHealth/AgentHealthReporterTests.cs
  tests/Agent/UnitTests/Core.UnitTest/WireModels/MetricWireModelTests.cs
Labels: feature

#933 Sets up LogEventAggregator to capture logs from inside and outside transactions
  src/Agent/NewRelic/Agent/Core/Agent.cs
  src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs
  src/Agent/NewRelic/Agent/Core/DependencyInjection/AgentServices.cs
  src/Agent/NewRelic/Agent/Core/Transactions/NoOpTransaction.cs
  src/Agent/NewRelic/Agent/Core/Transactions/Transaction.cs
  src/Agent/NewRelic/Agent/Core/Transactions/TransactionService.cs
  src/Agent/NewRelic/Agent/Core/Transformers/TransactionTransformer/TransactionTransformer.cs
  src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModel.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/IAgentExperimental.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/ITransactionExperimental.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs
  tests/Agent/UnitTests/Core.UnitTest/AgentHealth/AgentHealthReporterTests.cs
  tests/Agent/UnitTests/Core.UnitTest/CrossAgentTests/CatMapTests.cs
  tests/Agent/UnitTests/Core.UnitTest/CrossAgentTests/ServerSentEvent/ServerSentEventTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transactions/TransactionTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerSqlTraceTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Transformers/TransactionTransformer/TransactionTransformerTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs
Labels: feature

#934 Adds log decorating to log4net wrapper with config
  src/Agent/NewRelic/Agent/Core/Config/Configuration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs
Labels: feature

#932 Integration tests pass on Alpine
  tests/Agent/IntegrationTests/IntegrationTestHelpers/SkipAttributes.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/Utilities.cs
  tests/Agent/IntegrationTests/IntegrationTests/InfiniteTracing/InfiniteTracingTests.cs
Labels: testing

#945 Refactors local log decoration to use a single entry
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/Log4netWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Logging/LoggingHelpers.cs
Labels: enhancement

#946 Update broken link in CHANGELOG
  src/Agent/CHANGELOG.md
Labels: chore

#953 Loglevel naming update
  src/Agent/NewRelic/Agent/Core/Agent.cs
Labels: enhancement

#955 Use kibibytes instead of kilobytes for log message limit
  src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModel.cs
  tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelTests.cs
Labels: enhancement

#964 Adds request method to CallVendorApi for IMDSv2
  src/Agent/NewRelic/Agent/Core/Utilization/VendorHttpApiRequestor.cs
  src/Agent/NewRelic/Agent/Core/Utilization/VendorInfo.cs
  tests/Agent/UnitTests/Core.UnitTest/Utilization/VendorHttpApiRequestorTests.cs
Labels: enhancement

#965 Migrate AWS metadata to use IMDSv2
  src/Agent/NewRelic/Agent/Core/Utilization/VendorInfo.cs
Labels: enhancement

#978 Async Log4net forwarding integration test coverage
  tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs
  tests/Agent/IntegrationTests/IntegrationTests/Logging/Log4netMetricsAndForwardingTests.cs
  tests/Agent/IntegrationTests/SharedApplications/Common/MultiFunctionApplicationHelpers/NetStandardLibraries/LogInstrumentation/Log4netTester.cs
Labels: feature
