Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2022-03, with the labels that each got.

#991 Update log_event_data json to use `trace.id` and `span.id`
  src/Agent/NewRelic/Agent/Core/JsonConverters/LogEventWireModelCollectionJsonConverter.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/LogData.cs
  tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LogEventWireModelCollectionJsonConverterTests.cs
Labels: bug, enhancement

#1040 Adds test for server sending back 0 for maxSamples
  tests/Agent/IntegrationTests/IntegrationTests/Logging/ZeroMaxSamplesStoredTests.cs
Labels: enhancement

#1042 Updates changelong with deprecations
  src/Agent/CHANGELOG.md
Labels: chore
