Repository newrelic/newrelic-dotnet-agent, pull requests merged in 2022-06, with the labels that each got.

#1135 Add Code Level Metrics for CodeStream integration
  .github/workflows/all_solutions.yml
  src/Agent/CHANGELOG.md
  src/Agent/NewRelic/Agent/Core/Attributes/AttributeDefinitionService.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.cs
  src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
  src/Agent/NewRelic/Agent/Core/Configuration/DefaultConfiguration.cs
  src/Agent/NewRelic/Agent/Core/Segments/NoOpSegment.cs
  src/Agent/NewRelic/Agent/Core/Segments/Segment.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Api/Experimental/ISegmentExperimental.cs
  src/Agent/NewRelic/Agent/Extensions/NewRelic.Agent.Extensions/Configuration/IConfiguration.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/AspNetCore/InvokeActionMethodAsyncWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Mvc3/AsyncBeginInvokeActionWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Mvc3/AsyncEndInvokeActionWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Mvc3/GetControllerInstanceWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Mvc3/HandleUnknownActionWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Mvc3/InvokeExceptionFiltersWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Mvc3/MvcRouteNamingHelper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Mvc3/SyncInvokeActionWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/WebApi2/InvokeActionAsyncWrapper.cs
  tests/Agent/IntegrationTests/Applications/AgentApiExecutor/Program.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/NewRelicConfigModifier.cs
  tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/AspNetCoreMvcCodeAttributeTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/FrameworkAspNetMvcCodeAttributeTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/FrameworkCustomInstrumentationCodeAttributeTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/NetCoreCustomInstrumentationCodeAttributeTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/OwinWebApi2CodeAttributeTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/CodeLevelMetrics/WebApi2CodeAttributeTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Configuration/DefaultConfigurationTests.cs
Labels: feature

#1133 Update and fix Home.csproj to make errors more visible
  src/Agent/NewRelic/Home/Home.csproj
Labels: bug, on-hold

#1137 Updates gRPC Google.Protobuf to latest version
  .github/workflows/all_solutions.yml
  src/Agent/NewRelic/Agent/Core/Core.csproj
Labels: bug

#1144 Update logging attributes to match spec
  src/Agent/NewRelic/Agent/Core/Agent.cs
  src/Agent/NewRelic/Agent/Core/AgentHealth/AgentHealthReporter.cs
  src/Agent/NewRelic/Agent/Core/JsonConverters/LogEventWireModelCollectionJsonConverter.cs
  src/Agent/NewRelic/Agent/Core/WireModels/LogEventWireModel.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/Log4NetLogging/Log4netWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/MicrosoftExtensionsLogging/MicrosoftLoggingWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/NLogLogging/NLogWrapper.cs
  src/Agent/NewRelic/Agent/Extensions/Providers/Wrapper/SerilogLogging/NewRelicSerilogSink.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/Assertions.cs
  tests/Agent/IntegrationTests/IntegrationTestHelpers/Models/LogData.cs
  tests/Agent/IntegrationTests/IntegrationTests/Logging/MaxSamplesStoredTests.cs
  tests/Agent/IntegrationTests/IntegrationTests/Logging/MetricsAndForwardingTests.cs
  tests/Agent/UnitTests/Core.UnitTest/JsonConverters/LogEventWireModelCollectionJsonConverterTests.cs
  tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelCollectionTests.cs
  tests/Agent/UnitTests/Core.UnitTest/WireModels/LogEventWireModelTests.cs
  tests/Agent/UnitTests/Core.UnitTest/Wrapper/AgentWrapperApi/AgentWrapperApiTests.cs
Labels: chore
